# Local developer-mode targets.

.PHONY: enable-dev-strict
enable-dev-strict:
	mkdir -p "$(dir $(DEV_STRICT_CONFIG))"
	{ \
	  printf '%s\n' "# Local chengdu developer strict-mode config."; \
	  printf '%s\n' "# Generated by: make enable-dev-strict"; \
	  printf '%s\n' "# This file is intentionally ignored under build/."; \
	  printf '%s\n' "CHENGDU_DEV_STRICT := 1"; \
	} > "$(DEV_STRICT_CONFIG)"
	printf '%b\n' "$(GREEN)Developer strict mode enabled in $(DEV_STRICT_CONFIG)$(RESET)"
	printf '%b\n' "$(CYAN)Future make invocations will require strict developer test dependencies.$(RESET)"

.PHONY: disable-dev-strict
disable-dev-strict:
	rm -f "$(DEV_STRICT_CONFIG)"
	printf '%b\n' "$(YELLOW)Developer strict mode disabled; removed $(DEV_STRICT_CONFIG)$(RESET)"

.PHONY: dev-strict-status
dev-strict-status:
	printf '%s\n' "CHENGDU_DEV_STRICT=$(CHENGDU_DEV_STRICT)"
	printf '%s\n' "PANDAPI_REQUIRE_CATCH2=$(PANDAPI_REQUIRE_CATCH2)"
	if [ -f "$(DEV_STRICT_CONFIG)" ]; then \
	  printf '%s\n' "config=$(DEV_STRICT_CONFIG)"; \
	else \
	  printf '%s\n' "config=(not enabled; run make enable-dev-strict)"; \
	fi
